version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=admin
      - DB_HOST=devices.czkg0cwk08r1.sa-east-1.rds.amazonaws.com
      - DB_NAME=devices
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5000:5000"
